columnSuffix: null
handle: city
instructions: null
name: City
searchable: false
settings:
  maxLength: 255
  showLabelField: false
  showTargetField: false
  typeSettings:
    __assoc__:
      -
        - entry
        -
          __assoc__:
            -
              - sources
              -
                - 'section:88c4ebcc-2a76-47a3-9fce-05f5449ccefa' # Location
  types:
    - entry
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
